language: scala
scala:
# - 2.11.8
  - 2.12.4
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
