language: scala
scala:
# - 2.11.8
  - 2.12.3
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION desktopApp/compile meta-tests/coverage meta-tests/coverageReport meta-tests/test
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
