name: Build EXE

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: version
        run: |
          git fetch --prune --unshallow
          git checkout master
          $GitMessage = (git log -1 --pretty=%B) | Out-String
          $VersionMsgRegex = "Version ([0-9]+\.[0-9]+\.?[0-9]*)\s*"

          if ($GitMessage -match $VersionMsgRegex) {
            $Version = $Matches[1]
          } else {
            $VersionTag = (git describe --tags --abbrev=0) | Out-String
            $Version = $VersionTag.SubString(1)
          }
          Write-Output "::set-output name=version::$Version"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk+fx
      - name: Package EXE
        run: |
          choco uninstall -y InnoSetup
          choco install -y InnoSetup --version=5.6.1

          $Version="${{steps.version.outputs.version}}"
          $Universal="desktop-app/target/universal"
          $JPBundles="$Universal/jdkpackager/bundles"

          $env:JAVA_OPTS="-Xmx4G -Denable-tika=1 -Denable-javacv=1"
          sbt desktopApp/jdkPackager:packageBin
          move "$JPBundles\shadowcloud-$Version.exe" "$JPBundles\shadowcloud-full-$Version.exe"

          $env:JAVA_OPTS="-Xmx4G -Denable-tika=0 -Denable-javacv=0"
          sbt desktopApp/jdkPackager:packageBin
          move "$JPBundles\shadowcloud-$Version.exe" "$JPBundles\shadowcloud-light-$Version.exe"
      - uses: actions/upload-artifact@v2-preview
        with:
          name: shadowcloud-windows
          path: ${{github.workspace}}/desktop-app/target/universal/jdkpackager/bundles
