name: Build PKG

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: version
        run: |
          git fetch --prune --unshallow
          git checkout master
          export GitMessage=$(git log -1 --pretty=%B)
          VersionMsgRegex='Version ([0-9]+\.[0-9]+\.?[0-9]*).*'
          if [[ $GitMessage =~ $VersionMsgRegex ]]; then
            export Version="${BASH_REMATCH[1]}"
          else
            export VersionTag=$(git describe --tags --abbrev=0)
            export Version="${VersionTag:1}"
          fi
          echo "::set-output name=version::$Version"
      - name: Package PKG
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 8.0.252.fx-zulu
          sdk install sbt 1.3.8
          sdk use java 8.0.252.fx-zulu
          sdk use sbt 1.3.8

          Version="${{steps.version.outputs.version}}"
          Universal="${{github.workspace}}/desktop-app/target/universal"
          JPBundles="$Universal/jdkpackager/bundles"

          JAVA_OPTS="-Xmx4G -Denable-tika=0 -Denable-javacv=0" sbt "set jdkPackagerType in desktopApp :=\"pkg\"" desktopApp/jdkPackager:packageBin
          mv "$JPBundles/shadowcloud-$Version.pkg" "$JPBundles/shadowcloud-light-$Version.pkg"

          JAVA_OPTS="-Xmx4G -Denable-tika=1 -Denable-javacv=1" sbt "set jdkPackagerType in desktopApp :=\"pkg\"" desktopApp/jdkPackager:packageBin
          mv "$JPBundles/shadowcloud-$Version.pkg" "$JPBundles/shadowcloud-full-$Version.pkg"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{github.workspace}}/desktop-app/target/universal/jdkpackager/bundles/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
