name: Build DEB

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: version
        run: |
          git fetch --prune --unshallow
          git checkout master
          GitMessage=$(git log -1 --pretty=%B)
          VersionMsgRegex='Version ([0-9]+\.[0-9]+\.?[0-9]*).*'
          if [[ $GitMessage =~ $VersionMsgRegex ]]; then
            Version="${BASH_REMATCH[1]}"
          else
            VersionTag=$(git describe --tags --abbrev=0)
            Version="${VersionTag:1}"
          fi
          echo "::set-output name=version::$Version"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk+fx
      - name: Package DEB
        run: |
          Version="${{steps.version.outputs.version}}"
          Universal="${{github.workspace}}/desktop-app/target/universal"
          JPBundles="$Universal/jdkpackager/bundles"
          
          JAVA_OPTS="-Xmx4G -Denable-tika=1 -Denable-javacv-all=1" sbt desktopApp/universal:packageBin
          mv "$Universal/shadowcloud-$Version.zip" "$Universal/shadowcloud-full-$Version.zip"

          JAVA_OPTS="-Xmx4G -Denable-tika=1 -Denable-javacv=1" sbt desktopApp/jdkPackager:packageBin
          mv "$JPBundles/shadowcloud-$Version.deb" "$JPBundles/shadowcloud-full-$Version.deb"
          mv "$JPBundles/shadowcloud-$Version-1.x86_64.rpm" "$JPBundles/shadowcloud-full-$Version-1.x86_64.rpm"

          JAVA_OPTS="-Xmx4G -Denable-tika=0 -Denable-javacv=0" sbt desktopApp/jdkPackager:packageBin desktopApp/universal:packageBin
          mv "$JPBundles/shadowcloud-$Version.deb" "$JPBundles/shadowcloud-light-$Version.deb"
          mv "$JPBundles/shadowcloud-$Version.rpm-1.x86_64" "$JPBundles/shadowcloud-light-$Version-1.x86_64.rpm"
          mv "$Universal/shadowcloud-$Version.zip" "$Universal/shadowcloud-light-$Version.zip"
      - uses: actions/upload-artifact@v2-preview
        with:
          name: shadowcloud-linux
          path: ${{github.workspace}}/desktop-app/target/universal/jdkpackager/bundles
      - uses: actions/upload-artifact@v2-preview
        with:
          name: shadowcloud-universal
          path: ${{github.workspace}}/desktop-app/target/universal/*.zip
