name: Publish docker image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk+fx
      - uses: azure/docker-login@v1
        with:
          username: karasiq
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish docker image
        run: |
          sbt consoleApp/docker:publish
